JWKS: https://eauth-dev.ess-test.vimpelcom.ru/.well-known/jwks/
server:
  forward-headers-strategy: NATIVE
  use-forward-header: true
integration:
  products-server-url: https://fdm-products-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
  cx-server-url: https://cx-backend-func-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
  auth-server-url:  https://fdm-auth-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
  techradar-server-url: https://techradar-backend-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
  arch-server-url: http://localhost:8086
  pack-loader-server-url: http://localhost:8083
  capability-server-url: http://localhost:8083
  document-server-url: http://localhost:8083
  dashboard-server-url: https://dashboard-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
  notification-server-url: http://localhost:8082
  camunda-server-url: http://localhost:8082
#integration:
#  products-server-url: https://fdm-products-dev-service:8080
#  cx-server-url: https://cx-backend-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
#  auth-server-url: https://fdm-auth-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
#  techradar-server-url: https://techradar-backend-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
#  arch-server-url: https://structurizr-backend-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
#  pack-loader-server-url: https://fdm-pack-loader-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
#  capability-server-url: https://capability-backend-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
#  document-server-url: https://document-service-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
#  dashboard-server-url: https://dashboard-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
#  notification-server-url: https://fdm-notifications-management-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
#  camunda-server-url: https://fdm-bpm-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
