JWKS: https://eafdmmart--test-yd-wiremock.apps.yd-m6-kt22.vimpelcom.ru/.well-known/jwks/

integration:
  user-server-url: http://localhost:8083

service-url:
  cx: http://localhost:8082
  auth: http://localhost:8083
  techradar: http://localhost:8084