JWKS: https://eauth-dev.ess-test.vimpelcom.ru/.well-known/jwks/

integration:
  cx-server-url: http://cx-backend-func-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
  auth-server-url:  https://fdm-auth-func-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
  techradar-server-url: http://localhost:8086
  pack-loader-server-url: http://localhost:8082
  capability-server-url: https://dashboard-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
  dashboard-server-url: https://dashboard-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
