JWKS: https://eafdmmart--test-yd-wiremock.apps.yd-m6-kt22.vimpelcom.ru/.well-known/jwks/

integration:
  cx-server-url: http://localhost:8082
  auth-server-url: https://fdm-auth-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
  techradar-server-url: https://techradar-backend-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
