env:
  SPRING_PROFILES_ACTIVE: dev
  JWKS: "vault:eafdmmart/data/dev/fdm#jwks"
  integration:
    user-server-url: http://fdm-auth-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru

  spring:
    main:
      web-application-type: reactive
    cloud:
      gateway:
        routes:
          - id: cxBi
            uri: https://cx-backend-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
            predicates:
              - Path=/api/cx/v1/bi/**
            filters:
              - RewritePath=/api/cx/v1/bi/(?<RID>.*), /api/cx/v1/library/business-interactions/$\{RID}
          - id: cxRefference
            uri: https://cx-backend-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
            predicates:
              - Path=/api/cx/v1/references/**
            filters:
              - RewritePath=/api/cx/v1/references/(?<RID>.*), /api/cx/v1/references/$\{RID}
          - id: cxCj
            uri: https://cx-backend-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
            predicates:
              - Path=/api/cx/v1/cj/**
            filters:
              - RewritePath=/api/cx/v1/cj/(?<RID>.*), /api/cx/v1/product/cj/$\{RID}
          - id: cxProduct
            uri: https://cx-backend-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
            predicates:
              - Path=/api/cx/v1/product/**
            filters:
              - RewritePath=/api/cx/v1/product/(?<RID>.*), /api/cx/v1/product/$\{RID}
          - id: userService
            uri: https://fdm-auth-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
            predicates:
              - Path=api/auth/v1/**
            filters:
              - RewritePath=/api/auth/v1/(?<RID>.*), /api/admin/v1/$\{RID}
              - RewritePath=/api/auth/v1/user/(?<login>.+), /api/admin/v1/user/$\{login}
              - RewritePath=/api/auth/v1/user/(?<id>.*?)/product, /api/user/$\{id}/product
          - id: technoradar
            uri: https://techradar-backend-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
            predicates:
              - Path=api/techradar/v1/**
            filters:
              - RewritePath=/api/techradar/v1/(?<RID>.*), /api/v1/$\{RID}
              - RewritePath=/api/techradar/v1/tech, /api/v1/tech
