env:
  SPRING_PROFILES_ACTIVE: e2e
  JWKS: "vault:eafdmmart/data/test/e2e/fdm#jwks"
  INTEGRATION_CX_SERVER_URL: "vault:eafdmmart/data/test/e2e/fdm#cxserverurl"
  INTEGRATION_AUTH_SERVER_URL: "vault:eafdmmart/data/test/e2e/fdm#authserverurl"
  INTEGRATION_TECHRADAR_SERVER_URL: "vault:eafdmmart/data/test/e2e/fdm#techradarserverurl"
  INTEGRATION_PACK_LOADER_SERVER_URL: "vault:eafdmmart/data/test/e2e/fdm#packloaderserver"
  INTEGRATION_CAPABILITY_SERVER_URL: "vault:eafdmmart/data/test/e2e/fdm#capabilityserver"
  INTEGRATION_DASHBOARD_SERVER_URL: "vault:eafdmmart/data/test/e2e/fdm#dashboardserver"
  INTEGRATION_NOTIFICATION_SERVER_URL: "vault:eafdmmart/data/test/e2e/fdm#notificationserver"
  INTEGRATION_PRODUCTS_SERVER_URL: "vault:eafdmmart/data/test/e2e/fdm#productsserver"
  INTEGRATION_DOCUMENT_SERVER_URL: "vault:eafdmmart/data/test/e2e/fdm#documentserverurl"
  INTEGRATION_CAMUNDA_SERVER_URL: "vault:eafdmmart/data/test/e2e/fdm#camundaserverurl"
  INTEGRATION_ARCH_SERVER_URL: "vault:eafdmmart/data/test/e2e/fdm#archserverurl"
  INTEGRATION_GRAPH_SERVER_URL: "vault:eafdmmart/data/test/e2e/fdm#graphserverurl"

podAnnotations:
  vault.security.banzaicloud.io/vault-addr: "https://vault-test.vimpelcom.ru/"

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-headers: Content-Type, authorization, Content-Disposition
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST, PUT, DELETE, OPTIONS, PATCH
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-expose-headers: "Content-Disposition"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m

