env:
  SPRING_PROFILES_ACTIVE: e2e
  JWKS: "vault:eafdmmart/data/test/e2e/fdm#jwks"
  INTEGRATION_CX_SERVER_URL: "vault:eafdmmart/data/test/e2e/fdm#cxserverurl"
  INTEGRATION_AUTH_SERVER_URL: "vault:eafdmmart/data/test/e2e/fdm#authserverurl"
  INTEGRATION_TECHRADAR_SERVER_URL: "vault:eafdmmart/data/test/e2e/fdm#techradarserverurl"
  INTEGRATION_PACK_LOADER_SERVER_URL: "vault:eafdmmart/data/test/e2e/fdm#packloaderserver"
  INTEGRATION_CAPABILITY_SERVER_URL: "vault:eafdmmart/data/test/e2e/fdm#capabilityserver"
  INTEGRATION_DASHBOARD_SERVER_URL: "vault:eafdmmart/data/test/e2e/fdm#dashboardserver"

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-headers: Content-Type, authorization
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST, PUT, DELETE, OPTIONS, PATCH
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/enable-cors: 'true'


