env:
  SPRING_PROFILES_ACTIVE: prod
  JWKS: "vault:eafdmmart/data/prod/fdm#jwks"
  INTEGRATION_CX_SERVER_URL: "vault:eafdmmart/data/prod/fdm#cxserverurl"
  INTEGRATION_AUTH_SERVER_URL: "vault:eafdmmart/data/prod/fdm#authserverurl"
  INTEGRATION_TECHRADAR_SERVER_URL: "vault:eafdmmart/data/prod/fdm#techradarserverurl"
  INTEGRATION_PACK_LOADER_SERVER_URL: "vault:eafdmmart/data/prod/fdm#packloaderserver"
  INTEGRATION_CAPABILITY_SERVER_URL: "vault:eafdmmart/data/prod/fdm#capabilityserver"
  INTEGRATION_DASHBOARD_SERVER_URL: "vault:eafdmmart/data/prod/fdm#dashboardserver"
  INTEGRATION_NOTIFICATION_SERVER_URL: "vault:eafdmmart/data/prod/fdm#notificationserver"
  INTEGRATION_PRODUCTS_SERVER_URL: "vault:eafdmmart/data/prod/fdm#productsserver"

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-headers: Content-Type, authorization, Content-Disposition
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST, PUT, DELETE, OPTIONS, PATCH
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-expose-headers: "Content-Disposition"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
